(define (problem task)
(:domain turtlebot_mdp)
(:objects wp0 wp1 wp2 wp3 wp4 - waypoint r1 - robot)
(:init
    (robot_at r1 wp0)
    (docked r1)
    (dock_at wp0)
)
(:goal (and
    (visited wp0)
    (visited wp1)
    (visited wp2)
    (visited wp3)
    (visited wp4)
    (docked r1)
))
)
